	
// 配置方法
import 'Widget/font.js'
// 弹窗
import 'Widget/notice.js'
// 路由
import 'Widget/router.js'
// 发送请求
import 'Widget/axios.js'
// 获取地理位置
import 'Widget/geo.js'
// 获取相机信息
import 'Widget/camera.js'
// 设置导航
import 'Widget/nav.js'
// 支付相关
import 'Widget/pay.js'
// 存储相关
import 'Widget/storage.js'
// 全局事件
import 'Widget/events.js'
// 分享
import 'Widget/share.js'
// 工具方法
import 'Widget/tools.js'
